apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ashta-lakshmi.fullname" . }}-config
  labels:
    {{- include "ashta-lakshmi.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
